# Generated by Django 5.1.6 on 2025-03-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_resume_file_resume_resume_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
