# Generated by Django 5.1.6 on 2025-03-02 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
