# Generated by Django 5.1.6 on 2025-03-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_resume_ats_score_resume_shortlisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_threshold', models.FloatField(default=0.5)),
            ],
        ),
    ]
