# Generated by Django 5.1.6 on 2025-03-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_hrsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
