# Generated by Django 5.1.6 on 2025-03-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_resume_email_resume_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
