# Generated by Django 5.1.6 on 2025-03-06 13:26

import resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_resume_extracted_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='resumes/', validators=[resume.models.validate_resume_file]),
        ),
    ]
